datadump.location:
  author: /Users/sagnikdas/spring/test-authors.txt
  works: /Users/sagnikdas/spring/test-works.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: lpOJJotMscoZAeeGZTbXQXCa
      password: FLxIff532isThsZSOnZqku8hPaBICQH.Jnfk-My9542qxBa4frcJxtcw7rQOqjo+useLKIvr22Cy+MB2vPWpb+bK4msRssw+plIhmA9ioGQy+v+JhNXJFzfnAGkZ_994
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  main:
    allow-circular-references: true



datastax.astra:
  secure-connect-bundle: secure-connect.zip


astra.db:
  id: e09c35e7-8cbf-43c6-b62b-a302206f7ca9
  region: asia-south1
  keyspace: main
  application.token: AstraCS:lpOJJotMscoZAeeGZTbXQXCa:ed496faa202b274e98929c53e936d7250eeff7c10c28473bdbbb6122b7441446





